#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("POLift.Resource", IsApplication=true)]

namespace POLift
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040022
			public const int Add30SecButton = 2130968610;
			
			// aapt resource value: 0x7f04000d
			public const int AddExerciseButton = 2130968589;
			
			// aapt resource value: 0x7f04001f
			public const int CountDownTextView = 2130968607;
			
			// aapt resource value: 0x7f04000a
			public const int CreateExerciseButton = 2130968586;
			
			// aapt resource value: 0x7f040024
			public const int CreateExerciseLink = 2130968612;
			
			// aapt resource value: 0x7f04000f
			public const int CreateRoutineButton = 2130968591;
			
			// aapt resource value: 0x7f040017
			public const int CreateRoutineLink = 2130968599;
			
			// aapt resource value: 0x7f040012
			public const int ExerciseDeleteButton = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int ExerciseEditButton = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int ExerciseItemName = 2130968592;
			
			// aapt resource value: 0x7f040001
			public const int ExerciseNameText = 2130968577;
			
			// aapt resource value: 0x7f040013
			public const int ExerciseSetsLayout = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int ExerciseSetsName = 2130968597;
			
			// aapt resource value: 0x7f04000e
			public const int ExercisesListView = 2130968590;
			
			// aapt resource value: 0x7f04001a
			public const int NextExerciseView = 2130968602;
			
			// aapt resource value: 0x7f04001c
			public const int PlateMathTextView = 2130968604;
			
			// aapt resource value: 0x7f040003
			public const int RepRangeMaxText = 2130968579;
			
			// aapt resource value: 0x7f04001d
			public const int RepResultEditText = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int ReportResultButton = 2130968606;
			
			// aapt resource value: 0x7f040005
			public const int RestPeriodSecondsTextBox = 2130968581;
			
			// aapt resource value: 0x7f040019
			public const int RoutineDetails = 2130968601;
			
			// aapt resource value: 0x7f040023
			public const int RoutineResultTextView = 2130968611;
			
			// aapt resource value: 0x7f04000b
			public const int RoutineTitleText = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int RoutinesList = 2130968598;
			
			// aapt resource value: 0x7f040009
			public const int SelectMathTypeSpinner = 2130968585;
			
			// aapt resource value: 0x7f040014
			public const int SetCountText = 2130968596;
			
			// aapt resource value: 0x7f040021
			public const int SkipTimerButton = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int Sub30SecButton = 2130968608;
			
			// aapt resource value: 0x7f040028
			public const int TimeLeftTextView = 2130968616;
			
			// aapt resource value: 0x7f040018
			public const int ViewRecentSessionsButton = 2130968600;
			
			// aapt resource value: 0x7f040026
			public const int WarmupRoutineTextView = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int WarmupSetFinishedButton = 2130968615;
			
			// aapt resource value: 0x7f04001b
			public const int WeightEditText = 2130968603;
			
			// aapt resource value: 0x7f040007
			public const int WeightIncrementTextBox = 2130968583;
			
			// aapt resource value: 0x7f040025
			public const int WorkingSetWeightEditText = 2130968613;
			
			// aapt resource value: 0x7f040000
			public const int textView1 = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int textView10 = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int textView11 = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int textView12 = 2130968584;
			
			// aapt resource value: 0x7f04000c
			public const int textView2 = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int textView3 = 2130968578;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int CreateExercise = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CreateRoutine = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ExerciseItem = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ExerciseSetsItem = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int PerformRoutine = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int PlateMathItem = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int RoutineResult = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int SelectExercise = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int TimerControls = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int WarmupRoutine = 2130837514;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
